spring:
  application:
    name: smartBills

  datasource:
    url: jdbc:postgresql://localhost:5432/SmartBills
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: kumarsinghraunak27@gmail.com
    password: uaygglmgakwcmwfn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  elasticsearch:
    uris: http://localhost:9200

file:
  upload:
    url: upload/

debug: true
